import { RefreshCw, ShieldCheck, Sparkles } from "lucide-react";

import type { RuntimeStatus } from "../../shared/types.js";

export type StartupScreenMode = "starting" | "indexing" | "missingCodex" | "error";

interface StartupScreenProps {
  mode: StartupScreenMode;
  status: RuntimeStatus | null;
  error: string | null;
  onRetry: () => void;
}

export function StartupScreen({ mode, status, error, onRetry }: StartupScreenProps) {
  const content = getStartupContent(mode, status, error);
  const retryVisible = mode === "missingCodex" || mode === "error";
  const progress = status?.indexing.progress ?? null;
  const progressVisible = Boolean((mode === "indexing" || mode === "starting") && progress && progress.total > 0);
  const progressPercent =
    progressVisible && progress ? Math.max(0, Math.min(100, Math.round((progress.processed / progress.total) * 100))) : 0;

  return (
    <main className="startup-screen">
      <section className="startup-panel" aria-live="polite">
        <div className={mode === "indexing" || mode === "starting" ? "startup-mark spinning" : "startup-mark"}>
          {mode === "missingCodex" ? <Sparkles size={24} /> : <ShieldCheck size={24} />}
        </div>
        <p className="startup-kicker">Codex Desktop Companion</p>
        <h1>{content.title}</h1>
        <p>{content.body}</p>
        {progressVisible ? (
          <div className="startup-progress" aria-label="Indexing progress" aria-valuemax={100} aria-valuemin={0} aria-valuenow={progressPercent} role="progressbar">
            <span style={{ width: `${progressPercent}%` }} />
          </div>
        ) : null}
        <div className="startup-local-note">
          <ShieldCheck size={15} />
          <span>Completely local. No network connection is used for your library.</span>
        </div>
        {content.detail ? <small>{content.detail}</small> : null}
        {retryVisible ? (
          <button className="startup-retry" onClick={onRetry}>
            <RefreshCw size={16} />
            Retry
          </button>
        ) : null}
      </section>
    </main>
  );
}

function getStartupContent(
  mode: StartupScreenMode,
  status: RuntimeStatus | null,
  error: string | null
): { title: string; body: string; detail: string | null } {
  if (mode === "missingCodex") {
    return {
      title: "Codex Desktop data was not found",
      body: "CoMate is built specifically for images generated by the Codex desktop app.",
      detail: status
        ? `Expected local data under ${status.codexDesktop.codexRoot}`
        : "Open Codex Desktop and generate an image, then retry."
    };
  }

  if (mode === "error") {
    return {
      title: "The local library could not be indexed",
      body: "CoMate could not finish reading the Codex Desktop image library on this machine.",
      detail: error
    };
  }

  if (mode === "indexing") {
    const progress = status?.indexing.progress;
    const progressDetail =
      progress && progress.total > 0
        ? `${formatProgressPhase(progress.phase)} ${progress.processed} of ${progress.total} images.`
        : status?.indexing.indexed
          ? `${status.indexing.indexed} images indexed so far.`
          : null;
    return {
      title: "Building your local image library",
      body: "CoMate is scanning Codex Desktop images and linking them with session prompts.",
      detail: progressDetail
    };
  }

  return {
    title: "Starting CoMate",
    body: "Preparing the private local gallery for Codex Desktop images.",
    detail: null
  };
}

function formatProgressPhase(phase: RuntimeStatus["indexing"]["progress"]["phase"]): string {
  if (phase === "linking") {
    return "Linking prompts";
  }
  if (phase === "writing") {
    return "Writing index";
  }
  if (phase === "ready") {
    return "Ready";
  }
  return "Scanning";
}
